-- 코드를 입력하세요
SELECT
    P.PRODUCT_CODE,
    P.PRICE * SUM(S.SALES_AMOUNT) AS SALES
FROM
    PRODUCT AS P
    JOIN OFFLINE_SALE AS S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID
ORDER BY
    2 DESC,
    1